<a href="https://colab.research.google.com/github/Ghost970916/Ghost970916/blob/main/LaboratorioAA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio #1

In [3]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ejercicio #2

In [6]:
import numpy as np

x = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
print("x:\n{}".format(x))

x:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


Ejercicio #3

In [ ]:
import pandas as pd


myD1 = {
  "Ciudad": ["Habana","Tokio","Delhi","São Paulo","El Cairo"],
  "Poblacion": [80000,37270000,32060000, 22430000, 21750] ,
  "Pais": ["Cuba","Japon","India","Brasil","Egipto"],
}

myDf = pd.DataFrame(myD1, index = ["1", "2", "3", "4", "5"])
myDf


